- name: Create a image directory for container data
  ansible.builtin.file:
    path: "{{ container_parent_data_directory }}/{{ container_name }}"
    state: directory
    mode: "0755"

- name: Create the container
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: containrrr/watchtower
    state: started
    restart_policy: unless-stopped
    detach: true
    image_name_mismatch: "ignore"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    env:
      WATCHTOWER_CLEANUP: "true"
