docker_apt_filename: "docker"

docker_daemon_options:
  experimental: true
  ip6tables: true
  ipv6: true
  fixed-cidr-v6: "2001:db8:1::/64"

docker_apt_gpg_key_url: https://download.docker.com/linux/ubuntu/gpg
docker_apt_release_channel: stable
docker_apt_ansible_distribution: "{{ 'ubuntu' if ansible_distribution in ['Pop!_OS', 'Linux Mint'] else ansible_distribution }}"
docker_repo_url: https://download.docker.com/linux
docker_apt_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'armhf' if ansible_architecture == 'armv7l' else 'amd64' }}"
docker_apt_repository: "deb [arch={{ docker_apt_arch }} signed-by=/etc/apt/keyrings/docker.asc] {{ docker_repo_url }}/{{ docker_apt_ansible_distribution | lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"
