- name: Create a image directory for container data
  ansible.builtin.file:
    path: "{{ container_parent_data_directory }}/{{ container_name }}"
    state: directory
    mode: "0755"

- name: Create a data directory
  ansible.builtin.file:
    path: "{{ container_parent_data_directory }}/{{ container_name }}/data"
    state: directory
    mode: "0755"

- name: Create a logs directory
  ansible.builtin.file:
    path: "{{ container_parent_data_directory }}/{{ container_name }}/logs"
    state: directory
    mode: "0755"

# Note - Ports mappings must match env vars. Commented out for now due to defaults.
- name: Create the container
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: mbentley/omada-controller
    state: started
    restart_policy: unless-stopped
    detach: true
    stop_timeout: 60
    image_name_mismatch: "ignore"
    ulimits:
      - "nofile:4096:8192"
    ports:
      - "8088:8088"
      - "8043:8043"
      - "8843:8843"
      - "27001:27001/udp"
      - "29810:29810/udp"
      - "29811-29816:29811-29816"
    env:
      # MANAGE_HTTP_PORT: "8088"
      # MANAGE_HTTPS_PORT: "8043"
      # PGID: "508"
      # PORTAL_HTTP_PORT: "8088"
      # PORTAL_HTTPS_PORT: "8843"
      # PORT_ADOPT_V1: "29812"
      # PORT_APP_DISCOVERY: "27001"
      # PORT_DISCOVERY: "29810"
      # PORT_MANAGER_V1: "29811"
      # PORT_MANAGER_V2: "29814"
      # PORT_TRANSFER_V2: "29815"
      # PORT_RTTY: "29816"
      # PORT_UPGRADE_V1: "29813"
      # PUID: "508"
      # SHOW_SERVER_LOGS: "true"
      # SHOW_MONGODB_LOGS: "false"
      # SSL_CERT_NAME: "tls.crt"
      # SSL_KEY_NAME: "tls.key"
      # TZ: "Etc/UTC"
    volumes:
      - "{{ container_parent_data_directory }}/{{ container_name }}/data:/opt/tplink/EAPController/data"
      - "{{ container_parent_data_directory }}/{{ container_name }}/logs:/opt/tplink/EAPController/logs"
