- name: Update apt
  ansible.builtin.apt:
    update_cache: yes

- name: Install required dependencies
  ansible.builtin.apt:
    name:
      - software-properties-common
      - python3-debian

- name: Add ansible stable repository from PPA
  ansible.builtin.deb822_repository:
    name: ansible
    types: deb
    uris: https://ppa.launchpadcontent.net/ansible/ansible/ubuntu
    suites: "{{ ansible_distribution_release }}"
    components: main
    signed_by: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x6125E2A8C77F2818FB7BD15B93C4A3FD7BB9C367

- name: Update apt cache after adding ansible repository
  ansible.builtin.apt:
    update_cache: yes

- name: Install ansible
  ansible.builtin.apt:
    name: ansible
