- name: Set up static ip
  ansible.builtin.copy:
    src: 50-cloud-init.yaml
    dest: /etc/netplan/50-cloud-init.yaml
    owner: root
    group: root
    mode: "0600"
  register: static_ip_config

- name: Apply static ip config
  ansible.builtin.command: netplan apply
  when: static_ip_config.changed

- name: Update apt
  ansible.builtin.apt:
    update_cache: yes

- name: Upgrade the OS
  ansible.builtin.apt:
    upgrade: dist

- name: Install required system packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - bash
      - curl
      - dirmngr
      - git
      - gnupg
      - htop
      - nano
      - software-properties-common
      - unattended-upgrades
      - vim
      - wget
      - zsh

- name: Create a directory for all container data
  ansible.builtin.file:
    path: "{{ container_parent_data_directory }}"
    state: directory
    mode: "0755"

# Not a good idea for prod, but good for homelab
- name: Set up unattended-upgrades with a few more aggressive settings
  ansible.builtin.copy:
    src: 50unattended-upgrades
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: "0644"
  register: unattended_upgrade_config

- name: Restart unattended-upgrades if needed
  ansible.builtin.service:
    name: unattended-upgrades.service
    state: restarted
  when: unattended_upgrade_config.changed

- name: Set zsh as default shell for original user
  ansible.builtin.user:
    name: "{{ ansible_env.SUDO_USER }}"
    shell: "/usr/bin/zsh"

- name: Download Oh My Zsh
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/install_ohmyzsh.sh
  become: true
  become_user: "{{ ansible_env.SUDO_USER }}"

- name: Run Oh My Zsh installation script
  command: sh /tmp/install_ohmyzsh.sh --unattended
  register: ohmyzsh_result
  failed_when: "'FAILED' in ohmyzsh_result.stderr"
  become: true
  become_user: "{{ ansible_env.SUDO_USER }}"

- name: Download speedtest installer
  ansible.builtin.get_url:
    url: https://packagecloud.io/install/repositories/ookla/speedtest-cli/script.deb.sh
    dest: /tmp/speedtest-installer.sh

- name: Execute the speedtest installer
  ansible.builtin.shell: /tmp/speedtest-installer.sh

- name: Remove the speedtest installer
  ansible.builtin.file:
    path: /tmp/speedtest-installer.sh
    state: absent

- name: Install speedtest cli
  ansible.builtin.apt:
    name:
      - speedtest
