- name: Set up static ip
  ansible.builtin.copy:
    src: 50-cloud-init.yaml
    dest: /etc/netplan/50-cloud-init.yaml
    owner: root
    group: root
    mode: "0600"
  register: static_ip_config

- name: Apply static ip config
  ansible.builtin.command: netplan apply
  when: static_ip_config.changed

- name: Update apt
  ansible.builtin.apt:
    update_cache: yes

- name: Upgrade the OS
  ansible.builtin.apt:
    upgrade: dist

- name: Install required system packages
  ansible.builtin.apt:
    name:
      - bash
      - curl
      - git
      - htop
      - nano
      - software-properties-common
      - vim
      - wget

- name: Create a directory for all container data
  ansible.builtin.file:
    path: "{{ container_parent_data_directory }}"
    state: directory
    mode: "0755"
